### Bootstrapping the bounding boxes:
In this step we will use the finetuned model to generate new bounding boxes on the data that the model has not seen. The correctly predicted boxes will be used to further finetune the model and the incorrect boxes will be used to manually draw the bounding boxes in the images.

Steps:
1. Get the species and count from the preidcted bounding boxes (data in the folder - training_demo/Predictions/)
-- This is a TFRecord 

2. The LILA dataset does not have information on count and so I will use the concensus data for this information

In [1]:
#import pandas as pd
import csv, os, sys, io
import operator
import tensorflow as tf
import json
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as patches
sys.path.append('/home/ubuntu/data/tensorflow/my_workspace/camera-trap-detection/data/')
from utils import dataset_util
#Added this to handle the truncation error while decoding the jpeg
from PIL import ImageFile
from PIL import Image
ImageFile.LOAD_TRUNCATED_IMAGES = True

pd.options.display.max_columns = 100

In [2]:
Project_filepath = "/home/ubuntu/data/tensorflow/my_workspace/training_demo/"

In [3]:
with open('../data/LILA/SnapshotSerengeti.json', 'r') as f:
    dict1 = json.load(f)

# read the bounding box annotations and the image information to dataframes
df_annotations = pd.DataFrame(dict1['annotations'])
# Removing the unknown category from the dataset
df_annotations = df_annotations.loc[df_annotations['category_id']!=1000]
print(df_annotations.shape)
df_images = pd.DataFrame(dict1['images'])
print(df_images.shape)
df_categories = pd.DataFrame(dict1['categories'])
print(df_categories.shape)

(3241246, 3)
(3198737, 10)
(49, 2)

In [4]:
df_annotations.head()

,category_id,id,image_id
0,1,94cdea27-ad6d-11e8-88e9-000d3a062ba9,S1/B04/B04_R1/S1_B04_R1_PICT0001
1,1,94cdea29-ad6d-11e8-88e9-000d3a062ba9,S1/B04/B04_R1/S1_B04_R1_PICT0002
2,0,94cdea2b-ad6d-11e8-88e9-000d3a062ba9,S1/B04/B04_R1/S1_B04_R1_PICT0003
3,0,94cdea2d-ad6d-11e8-88e9-000d3a062ba9,S1/B04/B04_R1/S1_B04_R1_PICT0004
4,0,94cdea2f-ad6d-11e8-88e9-000d3a062ba9,S1/B04/B04_R1/S1_B04_R1_PICT0005

In [5]:
df_images.head()

,datetime,file_name,frame_num,height,id,location,season,seq_id,seq_num_frames,width
0,2010-07-18 16:26:14,S1/B04/B04_R1/S1_B04_R1_PICT0001.JPG,0,1536,S1/B04/B04_R1/S1_B04_R1_PICT0001,B04,S1,ASG0002kjh,1,2048
1,2010-07-18 16:26:30,S1/B04/B04_R1/S1_B04_R1_PICT0002.JPG,0,1536,S1/B04/B04_R1/S1_B04_R1_PICT0002,B04,S1,ASG0002kji,1,2048
2,NaN,S1/B04/B04_R1/S1_B04_R1_PICT0003.JPG,0,1536,S1/B04/B04_R1/S1_B04_R1_PICT0003,B04,S1,ASG0002kjj,1,2048
3,NaN,S1/B04/B04_R1/S1_B04_R1_PICT0004.JPG,0,1536,S1/B04/B04_R1/S1_B04_R1_PICT0004,B04,S1,ASG0002kjk,1,2048
4,NaN,S1/B04/B04_R1/S1_B04_R1_PICT0005.JPG,0,1536,S1/B04/B04_R1/S1_B04_R1_PICT0005,B04,S1,ASG0002kjl,1,2048

In [6]:
df_categories.head()

   id           name
0   0          empty
1   1          human
2   2  gazelleGrants
3   3       reedbuck
4   4         dikDik

# 1. Excluding the Schneider data
df_schneider_box = pd.read_csv('/home/ubuntu/data/tensorflow/my_workspace/training_demo/Data/GoldStandardBoundBoxCoord.csv')
schneider_events = list(set(df_schneider_box['filename']))
schneider_events = [word.split('.')[0] for word in schneider_events] # [word[:-4] for word in schneider_events]

In [10]:
# 2.
# Join the tables df_annotations and df_images
df_bb_meta = pd.merge(left=df_annotations, 
                      right=df_images, 
                      how='left',
                      left_on=df_annotations['image_id'], 
                      right_on=df_images['id'])
df_bb_meta = df_bb_meta.drop(columns=['key_0', 'id_y'])

df_bb_meta = pd.merge(left=df_bb_meta, 
                      right=df_categories, 
                      how='left',
                      left_on=df_bb_meta['category_id'], 
                      right_on=df_categories['id'])
df_bb_meta = df_bb_meta.drop(columns=['key_0', 'id'])
print("Shape before removing overlapping images with schneider's data: ", df_bb_meta.shape)

# Removing the overlapping images with Schneider's data
# df_bb_meta = df_bb_meta[~df_bb_meta['seq_id'].isin(schneider_events)]
# print("Shape after removing overlapping images with schneider's data: ", df_bb_meta.shape)

# 1.
# Removing the event that have been used for training the model
# event_in_training = list(df_bb_meta[df_bb_meta['image_id'].isin(l)]['seq_id'])
# df_bb_meta = df_bb_meta[~df_bb_meta['seq_id'].isin(event_in_training)]
# print("Shape after removing images used for training the model: ", df_bb_meta.shape)

# 2.
# Removing humans from the data
# df_bb_meta = df_bb_meta.loc[~df_bb_meta['category_id'].isin([0, 1])]
# print("Shape after removing human and empty images: ", df_bb_meta.shape)
# Converting the dataframe to th dictionary for convenience
# dict_bb_meta = df_bb_meta.to_dict('records')

Shape before removing overlapping images with schneider's data:  (3241246, 13)

In [11]:
df_bb_meta.head(n = 4)

,category_id,id_x,image_id,datetime,file_name,frame_num,height,location,season,seq_id,seq_num_frames,width,name
0,1,94cdea27-ad6d-11e8-88e9-000d3a062ba9,S1/B04/B04_R1/S1_B04_R1_PICT0001,2010-07-18 16:26:14,S1/B04/B04_R1/S1_B04_R1_PICT0001.JPG,0,1536,B04,S1,ASG0002kjh,1,2048,human
1,1,94cdea29-ad6d-11e8-88e9-000d3a062ba9,S1/B04/B04_R1/S1_B04_R1_PICT0002,2010-07-18 16:26:30,S1/B04/B04_R1/S1_B04_R1_PICT0002.JPG,0,1536,B04,S1,ASG0002kji,1,2048,human
2,0,94cdea2b-ad6d-11e8-88e9-000d3a062ba9,S1/B04/B04_R1/S1_B04_R1_PICT0003,NaN,S1/B04/B04_R1/S1_B04_R1_PICT0003.JPG,0,1536,B04,S1,ASG0002kjj,1,2048,empty
3,0,94cdea2d-ad6d-11e8-88e9-000d3a062ba9,S1/B04/B04_R1/S1_B04_R1_PICT0004,NaN,S1/B04/B04_R1/S1_B04_R1_PICT0004.JPG,0,1536,B04,S1,ASG0002kjk,1,2048,empty

In [12]:
df_concensus = pd.read_csv((Project_filepath + 'Data/consensus_data.csv'))
df_concensus.head(n = 2)

,CaptureEventID,NumImages,DateTime,SiteID,LocationX,LocationY,NumSpecies,Species,Count,Standing,Resting,Moving,Eating,Interacting,Babies,NumClassifications,NumVotes,NumBlanks,Evenness
0,ASG0002kjh,1,2010-07-18 16:26:14,B04,695238,9729497,1,human,1,0.625000,0.062500,0.0,0.000000,0.500000,0.0,17,16,1,0.0
1,ASG0002kji,1,2010-07-18 16:26:30,B04,695238,9729497,1,human,2,0.095238,0.619048,0.0,0.047619,0.333333,0.0,23,21,2,0.0

In [14]:
target = list(df_concensus['CaptureEventID'])
print(len(list(df_concensus['CaptureEventID'])))
print(len(set(df_concensus['CaptureEventID'])))

334671
319915

In [15]:
count_dict={}
for event in target:
    if event not in count_dict:
        count_dict[event] = 1
    else:
        count_dict[event] = count_dict[event] + 1

In [16]:
duplicates = {k : v for k,v in count_dict.items() if v > 3}
duplicates

{'ASG000q0hl': 4}

In [17]:
df_concensus[df_concensus['CaptureEventID'] == 'ASG000q0hl']

,CaptureEventID,NumImages,DateTime,SiteID,LocationX,LocationY,NumSpecies,Species,Count,Standing,Resting,Moving,Eating,Interacting,Babies,NumClassifications,NumVotes,NumBlanks,Evenness
259334,ASG000q0hl,3,2012-10-11 15:33:35,I01,710924,9735643,4,zebra,1,0.000,0.0,0.958333,0.041667,0.0,0.000000,25,24,0,0.774047
259335,ASG000q0hl,3,2012-10-11 15:33:35,I01,710924,9735643,4,warthog,4,0.000,0.0,1.000000,0.000000,0.0,0.695652,25,23,0,0.774047
259336,ASG000q0hl,3,2012-10-11 15:33:35,I01,710924,9735643,4,topi,1,0.000,0.0,1.000000,0.000000,0.0,0.000000,25,16,0,0.774047
259337,ASG000q0hl,3,2012-10-11 15:33:35,I01,710924,9735643,4,gazelleGrants,2,0.125,0.0,0.875000,0.000000,0.0,0.000000,25,8,0,0.774047

Bring in the info about the count to the all_image dataframe

In [12]:
df_image_wc = pd.merge(left=df_bb_meta,
        right=df_concensus,
        how='left',
        left_on=df_images['seq_id'],
        right_on=df_concensus['CaptureEventID'])
df_image_wc = df_image_wc.drop(columns=['key_0', 'CaptureEventID'])

KeyError: 0          ASG0002kjh
1          ASG0002kji
2          ASG0002kjj
3          ASG0002kjk
4          ASG0002kjl
5          ASG0002kjm
6          ASG0002kjn
7          ASG0002kjo
8          ASG0002kjp
9          ASG0002kjq
10         ASG0002kjr
11         ASG0002kjs
12         ASG0002kjt
13         ASG0002kju
14         ASG0002kjv
15         ASG0002kjw
16         ASG0002kjx
17         ASG0002kjy
18         ASG0002kjz
19         ASG0002kk0
20         ASG0002kk1
21         ASG0002kk2
22         ASG0002kk3
23         ASG0002kk4
24         ASG0002kk4
25         ASG0002kk4
26         ASG0002kk5
27         ASG0002kk5
28         ASG0002kk5
29         ASG0002kk6
              ...
3198707    ASG0011wg7
3198708    ASG0011wg7
3198709    ASG0011wg9
3198710    ASG0011wg9
3198711    ASG0011wg9
3198712    ASG0011wga
3198713    ASG0011wga
3198714    ASG0011wga
3198715    ASG0011wgb
3198716    ASG0011wgb
3198717    ASG0011wgb
3198718    ASG0011wgc
3198719    ASG0011wgc
3198720    ASG0011wgc
3198721    ASG0011wgd
3198722    ASG0011wgd
3198723    ASG0011wgd
3198724    ASG00072bs
3198725    ASG00072bs
3198726    ASG00072bs
3198727    ASG000yjtg
3198728    ASG000yjtg
3198729    ASG000yjtg
3198730    ASG000zsni
3198731    ASG000zsni
3198732    ASG000zsni
3198733    ASG00079q6
3198734    ASG000tvd0
3198735    ASG000tvd0
3198736    ASG000tvd0
Name: seq_id, Length: 3198737, dtype: object

In [22]:
print(df_image_wc.shape[0] - df_images.shape[0])
df_image_wc.head()

42509

,datetime,file_name,frame_num,height,id,location,season,seq_id,seq_num_frames,width,NumImages,DateTime,SiteID,LocationX,LocationY,NumSpecies,Species,Count,Standing,Resting,Moving,Eating,Interacting,Babies,NumClassifications,NumVotes,NumBlanks,Evenness
0,2010-07-18 16:26:14,S1/B04/B04_R1/S1_B04_R1_PICT0001.JPG,0,1536,S1/B04/B04_R1/S1_B04_R1_PICT0001,B04,S1,ASG0002kjh,1,2048,1.0,2010-07-18 16:26:14,B04,695238.0,9729497.0,1.0,human,1,0.625000,0.062500,0.0,0.000000,0.500000,0.0,17.0,16.0,1.0,0.0
1,2010-07-18 16:26:30,S1/B04/B04_R1/S1_B04_R1_PICT0002.JPG,0,1536,S1/B04/B04_R1/S1_B04_R1_PICT0002,B04,S1,ASG0002kji,1,2048,1.0,2010-07-18 16:26:30,B04,695238.0,9729497.0,1.0,human,2,0.095238,0.619048,0.0,0.047619,0.333333,0.0,23.0,21.0,2.0,0.0
2,NaN,S1/B04/B04_R1/S1_B04_R1_PICT0003.JPG,0,1536,S1/B04/B04_R1/S1_B04_R1_PICT0003,B04,S1,ASG0002kjj,1,2048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,S1/B04/B04_R1/S1_B04_R1_PICT0004.JPG,0,1536,S1/B04/B04_R1/S1_B04_R1_PICT0004,B04,S1,ASG0002kjk,1,2048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,S1/B04/B04_R1/S1_B04_R1_PICT0005.JPG,0,1536,S1/B04/B04_R1/S1_B04_R1_PICT0005,B04,S1,ASG0002kjl,1,2048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
l1 = list(set(df_images['seq_id']))
l2 = list(set(df_concensus['CaptureEventID']))
# [l1[i] for i in range(len(l1)) if l1[i] in l2]
len(list(set(df_images['seq_id']) & set(df_concensus['CaptureEventID'])))

319908

In [35]:
3198737 - df_concensus.shape[0]

2864066

Run through the TFRecord and check the count and list of animals. logic: <br>
1. Predictions Species, count per image
2. Ground truth Species, count per image from Concensus data or data prepped by marco

In [4]:
def decode_record(serialized_example):
    context_features = {
                        'image/filename': tf.FixedLenFeature([], tf.string),
                        'image/encoded': tf.FixedLenFeature([], tf.string),
                        'image/format': tf.FixedLenFeature([], tf.string),
                        "image/detection/bbox/xmin" : tf.VarLenFeature(tf.float32),
                        "image/detection/bbox/xmax" : tf.VarLenFeature(tf.float32),
                        "image/detection/bbox/ymin" : tf.VarLenFeature(tf.float32),
                        "image/detection/bbox/ymax" : tf.VarLenFeature(tf.float32),
                        "image/detection/label" : tf.VarLenFeature(tf.int64),
                        "image/detection/score" : tf.VarLenFeature(tf.float32)
                    }


    context, sequence = tf.parse_single_sequence_example(serialized=serialized_example,
                                              context_features=context_features,
#                                               sequence_features=sequence_features,
                                              example_name=None,
                                              name=None)

    return ({k: v for k, v in context.items()},{k: v for k, v in sequence.items()})

In [77]:
filename_list = ['/home/ubuntu/data/tensorflow/my_workspace/training_demo/Predictions/snapshot_serengeti_s01_s06-0-10000.record']
batch_size = 1
dataset = tf.data.Dataset.from_tensor_slices(filename_list)
dataset = tf.data.TFRecordDataset(dataset)
# dataset = dataset.shuffle(buffer_size=batch_size)
# dataset = dataset.repeat(1)
dataset = dataset.map(lambda x: decode_record(serialized_example=x)).batch(batch_size)

iterator = dataset.make_one_shot_iterator() # create the iterator
batch_data = iterator.get_next()

# print(dataset.output_types)
# print(dataset.output_shapes)

In [78]:
# batch_data = iterator.get_next()
with tf.Session() as sess:
    (context, sequence) = sess.run(batch_data)
    img = context['image/encoded'][0]
    # Detection 
    filename = context['image/filename']
    xmin_d = (context['image/detection/bbox/xmin'])
    ymin_d = (context['image/detection/bbox/ymin'])
    xmax_d = (context['image/detection/bbox/xmax'])
    ymax_d = (context['image/detection/bbox/ymax'])
    label_d = (context['image/detection/label'])
    score = (context['image/detection/score'])
    
    score_threshold = 0.5
    encoded_jpg_io = io.BytesIO(img)
    image = Image.open(encoded_jpg_io)
    width, height = image.size
    
    i = 0
    xmins_d, ymins_d, xmaxs_d, ymaxs_d, labels_d, scores = [], [], [], [], [], []

    for j in range(0, xmin_d[0].shape[0]):
        if xmin_d[0][j][0] == i and score[1][j]>=score_threshold:
            xmins_d.append(int(xmin_d[1][j]*width))
            ymins_d.append(int(ymin_d[1][j]*height))
            xmaxs_d.append(int(xmax_d[1][j]*width))
            ymaxs_d.append(int(ymax_d[1][j]*height))
            labels_d.append(label_d[1][j])
            scores.append(round(score[1][j]*100, 1))

In [79]:
context['image/detection/bbox/xmin']

SparseTensorValue(indices=array([[ 0,  0],
       [ 0,  1],
       [ 0,  2],
       [ 0,  3],
       [ 0,  4],
       [ 0,  5],
       [ 0,  6],
       [ 0,  7],
       [ 0,  8],
       [ 0,  9],
       [ 0, 10],
       [ 0, 11],
       [ 0, 12],
       [ 0, 13],
       [ 0, 14],
       [ 0, 15],
       [ 0, 16],
       [ 0, 17],
       [ 0, 18],
       [ 0, 19],
       [ 0, 20],
       [ 0, 21],
       [ 0, 22],
       [ 0, 23],
       [ 0, 24],
       [ 0, 25],
       [ 0, 26],
       [ 0, 27],
       [ 0, 28],
       [ 0, 29],
       [ 0, 30],
       [ 0, 31],
       [ 0, 32],
       [ 0, 33],
       [ 0, 34],
       [ 0, 35],
       [ 0, 36],
       [ 0, 37],
       [ 0, 38],
       [ 0, 39],
       [ 0, 40],
       [ 0, 41],
       [ 0, 42],
       [ 0, 43],
       [ 0, 44],
       [ 0, 45],
       [ 0, 46],
       [ 0, 47],
       [ 0, 48],
       [ 0, 49],
       [ 0, 50],
       [ 0, 51],
       [ 0, 52],
       [ 0, 53],
       [ 0, 54],
       [ 0, 55],
       [ 0, 56],
       [ 0, 57],
       [ 0, 58],
       [ 0, 59],
       [ 0, 60],
       [ 0, 61],
       [ 0, 62],
       [ 0, 63],
       [ 0, 64],
       [ 0, 65],
       [ 0, 66],
       [ 0, 67],
       [ 0, 68],
       [ 0, 69],
       [ 0, 70],
       [ 0, 71],
       [ 0, 72],
       [ 0, 73],
       [ 0, 74]]), values=array([0.35447586, 0.35034874, 0.35931507, 0.38577777, 0.32493898,
       0.34728947, 0.30087775, 0.34311253, 0.32428855, 0.338793  ,
       0.33718154, 0.26118416, 0.37068707, 0.3337175 , 0.31924954,
       0.3565906 , 0.36697128, 0.4031487 , 0.34903136, 0.34533438,
       0.35516655, 0.35425788, 0.30074564, 0.32234603, 0.3591262 ,
       0.3749118 , 0.35370883, 0.3342785 , 0.30659792, 0.33644125,
       0.3722968 , 0.36111253, 0.30157354, 0.35065016, 0.3808985 ,
       0.33131224, 0.33277708, 0.32537672, 0.3539009 , 0.34703583,
       0.33562362, 0.37821418, 0.38263106, 0.31913966, 0.3315553 ,
       0.32440192, 0.34541464, 0.36812073, 0.3518625 , 0.35086823,
       0.01591034, 0.6654858 , 0.48245886, 0.38707793, 0.67438644,
       0.02038318, 0.49792352, 0.02922655, 0.67533904, 0.6854739 ,
       0.03442344, 0.02255642, 0.0064411 , 0.5011709 , 0.00749242,
       0.0295031 , 0.02598085, 0.68445396, 0.66680187, 0.6707916 ,
       0.00942581, 0.48725036, 0.0217484 , 0.66822475, 0.6602628 ],
      dtype=float32), dense_shape=array([ 1, 75]))

In [50]:
(filename), labels_d, scores

(array([b'S1/B04/B04_R1/S1_B04_R1_PICT0009'], dtype=object), [5], [99.1])

In [22]:
db_dict = {}
with open('../data/LILA/db_export_season_all.csv', 'r') as csvfile:
    csvdata = csv.reader(csvfile, delimiter=',')
    header = next(csvdata)
    col_mapper = {k: i for i, k in enumerate(header)}
    for i, row in enumerate(csvdata):
        filename = row[col_mapper['PathFilename']]
        if filename not in db_dict.keys():
            db_dict[filename] = []
        db_dict[filename].append({k: row[v] for k, v in col_mapper.items() })
        if i%5000 == 0:
            print("performing iteration : %s" % i)

performing iteration : 0
performing iteration : 5000
performing iteration : 10000
performing iteration : 15000
performing iteration : 20000
performing iteration : 25000
performing iteration : 30000
performing iteration : 35000
performing iteration : 40000
performing iteration : 45000
performing iteration : 50000
performing iteration : 55000
performing iteration : 60000
performing iteration : 65000
performing iteration : 70000
performing iteration : 75000
performing iteration : 80000
performing iteration : 85000
performing iteration : 90000
performing iteration : 95000
performing iteration : 100000
performing iteration : 105000
performing iteration : 110000
performing iteration : 115000
performing iteration : 120000
performing iteration : 125000
performing iteration : 130000
performing iteration : 135000
performing iteration : 140000
performing iteration : 145000
performing iteration : 150000
performing iteration : 155000
performing iteration : 160000
performing iteration : 165000
performing iteration : 170000
performing iteration : 175000
performing iteration : 180000
performing iteration : 185000
performing iteration : 190000
performing iteration : 195000
performing iteration : 200000
performing iteration : 205000
performing iteration : 210000
performing iteration : 215000
performing iteration : 220000
performing iteration : 225000
performing iteration : 230000
performing iteration : 235000
performing iteration : 240000
performing iteration : 245000
performing iteration : 250000
performing iteration : 255000
performing iteration : 260000
performing iteration : 265000
performing iteration : 270000
performing iteration : 275000
performing iteration : 280000
performing iteration : 285000
performing iteration : 290000
performing iteration : 295000
performing iteration : 300000
performing iteration : 305000
performing iteration : 310000
performing iteration : 315000
performing iteration : 320000
performing iteration : 325000
performing iteration : 330000
performing iteration : 335000
performing iteration : 340000
performing iteration : 345000
performing iteration : 350000
performing iteration : 355000
performing iteration : 360000
performing iteration : 365000
performing iteration : 370000
performing iteration : 375000
performing iteration : 380000
performing iteration : 385000
performing iteration : 390000
performing iteration : 395000
performing iteration : 400000
performing iteration : 405000
performing iteration : 410000
performing iteration : 415000
performing iteration : 420000
performing iteration : 425000
performing iteration : 430000
performing iteration : 435000
performing iteration : 440000
performing iteration : 445000
performing iteration : 450000
performing iteration : 455000
performing iteration : 460000
performing iteration : 465000
performing iteration : 470000
performing iteration : 475000
performing iteration : 480000
performing iteration : 485000
performing iteration : 490000
performing iteration : 495000
performing iteration : 500000
performing iteration : 505000
performing iteration : 510000
performing iteration : 515000
performing iteration : 520000
performing iteration : 525000
performing iteration : 530000
performing iteration : 535000
performing iteration : 540000
performing iteration : 545000
performing iteration : 550000
performing iteration : 555000
performing iteration : 560000
performing iteration : 565000
performing iteration : 570000
performing iteration : 575000
performing iteration : 580000
performing iteration : 585000
performing iteration : 590000
performing iteration : 595000
performing iteration : 600000
performing iteration : 605000
performing iteration : 610000
performing iteration : 615000
performing iteration : 620000
performing iteration : 625000
performing iteration : 630000
performing iteration : 635000
performing iteration : 640000
performing iteration : 645000
performing iteration : 650000
performing iteration : 655000
performing iteration : 660000
performing iteration : 665000
performing iteration : 670000
performing iteration : 675000
performing iteration : 680000
performing iteration : 685000
performing iteration : 690000
performing iteration : 695000
performing iteration : 700000
performing iteration : 705000
performing iteration : 710000
performing iteration : 715000
performing iteration : 720000
performing iteration : 725000
performing iteration : 730000
performing iteration : 735000
performing iteration : 740000
performing iteration : 745000
performing iteration : 750000
performing iteration : 755000
performing iteration : 760000
performing iteration : 765000
performing iteration : 770000
performing iteration : 775000
performing iteration : 780000
performing iteration : 785000
performing iteration : 790000
performing iteration : 795000
performing iteration : 800000
performing iteration : 805000
performing iteration : 810000
performing iteration : 815000
performing iteration : 820000
performing iteration : 825000
performing iteration : 830000
performing iteration : 835000
performing iteration : 840000
performing iteration : 845000
performing iteration : 850000
performing iteration : 855000
performing iteration : 860000
performing iteration : 865000
performing iteration : 870000
performing iteration : 875000
performing iteration : 880000
performing iteration : 885000
performing iteration : 890000
performing iteration : 895000
performing iteration : 900000
performing iteration : 905000
performing iteration : 910000
performing iteration : 915000
performing iteration : 920000
performing iteration : 925000
performing iteration : 930000
performing iteration : 935000
performing iteration : 940000
performing iteration : 945000
performing iteration : 950000
performing iteration : 955000
performing iteration : 960000
performing iteration : 965000
performing iteration : 970000
performing iteration : 975000
performing iteration : 980000
performing iteration : 985000
performing iteration : 990000
performing iteration : 995000
performing iteration : 1000000
performing iteration : 1005000
performing iteration : 1010000
performing iteration : 1015000
performing iteration : 1020000
performing iteration : 1025000
performing iteration : 1030000
performing iteration : 1035000
performing iteration : 1040000
performing iteration : 1045000
performing iteration : 1050000
performing iteration : 1055000
performing iteration : 1060000
performing iteration : 1065000
performing iteration : 1070000
performing iteration : 1075000
performing iteration : 1080000
performing iteration : 1085000
performing iteration : 1090000
performing iteration : 1095000
performing iteration : 1100000
performing iteration : 1105000
performing iteration : 1110000
performing iteration : 1115000
performing iteration : 1120000
performing iteration : 1125000
performing iteration : 1130000
performing iteration : 1135000
performing iteration : 1140000
performing iteration : 1145000
performing iteration : 1150000
performing iteration : 1155000
performing iteration : 1160000
performing iteration : 1165000
performing iteration : 1170000
performing iteration : 1175000
performing iteration : 1180000
performing iteration : 1185000
performing iteration : 1190000
performing iteration : 1195000
performing iteration : 1200000
performing iteration : 1205000
performing iteration : 1210000
performing iteration : 1215000
performing iteration : 1220000
performing iteration : 1225000
performing iteration : 1230000
performing iteration : 1235000
performing iteration : 1240000
performing iteration : 1245000
performing iteration : 1250000
performing iteration : 1255000
performing iteration : 1260000
performing iteration : 1265000
performing iteration : 1270000
performing iteration : 1275000
performing iteration : 1280000
performing iteration : 1285000
performing iteration : 1290000
performing iteration : 1295000
performing iteration : 1300000
performing iteration : 1305000
performing iteration : 1310000
performing iteration : 1315000
performing iteration : 1320000
performing iteration : 1325000
performing iteration : 1330000
performing iteration : 1335000
performing iteration : 1340000
performing iteration : 1345000
performing iteration : 1350000
performing iteration : 1355000
performing iteration : 1360000
performing iteration : 1365000
performing iteration : 1370000
performing iteration : 1375000
performing iteration : 1380000
performing iteration : 1385000
performing iteration : 1390000
performing iteration : 1395000
performing iteration : 1400000
performing iteration : 1405000
performing iteration : 1410000
performing iteration : 1415000
performing iteration : 1420000
performing iteration : 1425000
performing iteration : 1430000
performing iteration : 1435000
performing iteration : 1440000
performing iteration : 1445000
performing iteration : 1450000
performing iteration : 1455000
performing iteration : 1460000

performing iteration : 1465000
performing iteration : 1470000
performing iteration : 1475000
performing iteration : 1480000
performing iteration : 1485000
performing iteration : 1490000
performing iteration : 1495000
performing iteration : 1500000
performing iteration : 1505000
performing iteration : 1510000
performing iteration : 1515000
performing iteration : 1520000
performing iteration : 1525000
performing iteration : 1530000
performing iteration : 1535000
performing iteration : 1540000
performing iteration : 1545000
performing iteration : 1550000
performing iteration : 1555000
performing iteration : 1560000
performing iteration : 1565000
performing iteration : 1570000
performing iteration : 1575000
performing iteration : 1580000
performing iteration : 1585000
performing iteration : 1590000
performing iteration : 1595000
performing iteration : 1600000
performing iteration : 1605000
performing iteration : 1610000
performing iteration : 1615000
performing iteration : 1620000
performing iteration : 1625000
performing iteration : 1630000
performing iteration : 1635000
performing iteration : 1640000
performing iteration : 1645000
performing iteration : 1650000
performing iteration : 1655000
performing iteration : 1660000
performing iteration : 1665000
performing iteration : 1670000
performing iteration : 1675000
performing iteration : 1680000
performing iteration : 1685000
performing iteration : 1690000
performing iteration : 1695000
performing iteration : 1700000
performing iteration : 1705000
performing iteration : 1710000
performing iteration : 1715000
performing iteration : 1720000
performing iteration : 1725000
performing iteration : 1730000
performing iteration : 1735000
performing iteration : 1740000
performing iteration : 1745000
performing iteration : 1750000
performing iteration : 1755000
performing iteration : 1760000
performing iteration : 1765000
performing iteration : 1770000
performing iteration : 1775000
performing iteration : 1780000
performing iteration : 1785000
performing iteration : 1790000
performing iteration : 1795000
performing iteration : 1800000
performing iteration : 1805000
performing iteration : 1810000
performing iteration : 1815000
performing iteration : 1820000
performing iteration : 1825000
performing iteration : 1830000
performing iteration : 1835000
performing iteration : 1840000
performing iteration : 1845000
performing iteration : 1850000
performing iteration : 1855000
performing iteration : 1860000
performing iteration : 1865000
performing iteration : 1870000
performing iteration : 1875000
performing iteration : 1880000
performing iteration : 1885000
performing iteration : 1890000
performing iteration : 1895000
performing iteration : 1900000
performing iteration : 1905000
performing iteration : 1910000
performing iteration : 1915000
performing iteration : 1920000
performing iteration : 1925000
performing iteration : 1930000
performing iteration : 1935000
performing iteration : 1940000
performing iteration : 1945000
performing iteration : 1950000
performing iteration : 1955000
performing iteration : 1960000
performing iteration : 1965000
performing iteration : 1970000
performing iteration : 1975000
performing iteration : 1980000
performing iteration : 1985000
performing iteration : 1990000
performing iteration : 1995000
performing iteration : 2000000
performing iteration : 2005000
performing iteration : 2010000
performing iteration : 2015000
performing iteration : 2020000
performing iteration : 2025000
performing iteration : 2030000
performing iteration : 2035000
performing iteration : 2040000
performing iteration : 2045000
performing iteration : 2050000
performing iteration : 2055000
performing iteration : 2060000
performing iteration : 2065000
performing iteration : 2070000
performing iteration : 2075000
performing iteration : 2080000
performing iteration : 2085000
performing iteration : 2090000
performing iteration : 2095000
performing iteration : 2100000
performing iteration : 2105000
performing iteration : 2110000
performing iteration : 2115000
performing iteration : 2120000
performing iteration : 2125000
performing iteration : 2130000
performing iteration : 2135000
performing iteration : 2140000
performing iteration : 2145000
performing iteration : 2150000
performing iteration : 2155000
performing iteration : 2160000
performing iteration : 2165000
performing iteration : 2170000
performing iteration : 2175000
performing iteration : 2180000
performing iteration : 2185000
performing iteration : 2190000
performing iteration : 2195000
performing iteration : 2200000
performing iteration : 2205000
performing iteration : 2210000
performing iteration : 2215000
performing iteration : 2220000
performing iteration : 2225000
performing iteration : 2230000
performing iteration : 2235000
performing iteration : 2240000
performing iteration : 2245000
performing iteration : 2250000
performing iteration : 2255000
performing iteration : 2260000
performing iteration : 2265000
performing iteration : 2270000
performing iteration : 2275000
performing iteration : 2280000
performing iteration : 2285000
performing iteration : 2290000
performing iteration : 2295000
performing iteration : 2300000
performing iteration : 2305000
performing iteration : 2310000
performing iteration : 2315000
performing iteration : 2320000
performing iteration : 2325000
performing iteration : 2330000
performing iteration : 2335000
performing iteration : 2340000
performing iteration : 2345000
performing iteration : 2350000
performing iteration : 2355000
performing iteration : 2360000
performing iteration : 2365000
performing iteration : 2370000
performing iteration : 2375000
performing iteration : 2380000
performing iteration : 2385000
performing iteration : 2390000
performing iteration : 2395000
performing iteration : 2400000
performing iteration : 2405000
performing iteration : 2410000
performing iteration : 2415000
performing iteration : 2420000
performing iteration : 2425000
performing iteration : 2430000
performing iteration : 2435000
performing iteration : 2440000
performing iteration : 2445000
performing iteration : 2450000
performing iteration : 2455000
performing iteration : 2460000
performing iteration : 2465000
performing iteration : 2470000
performing iteration : 2475000
performing iteration : 2480000
performing iteration : 2485000
performing iteration : 2490000
performing iteration : 2495000
performing iteration : 2500000
performing iteration : 2505000
performing iteration : 2510000
performing iteration : 2515000
performing iteration : 2520000
performing iteration : 2525000
performing iteration : 2530000
performing iteration : 2535000
performing iteration : 2540000
performing iteration : 2545000
performing iteration : 2550000
performing iteration : 2555000
performing iteration : 2560000
performing iteration : 2565000
performing iteration : 2570000
performing iteration : 2575000
performing iteration : 2580000
performing iteration : 2585000
performing iteration : 2590000
performing iteration : 2595000
performing iteration : 2600000
performing iteration : 2605000
performing iteration : 2610000
performing iteration : 2615000
performing iteration : 2620000
performing iteration : 2625000
performing iteration : 2630000
performing iteration : 2635000
performing iteration : 2640000
performing iteration : 2645000
performing iteration : 2650000
performing iteration : 2655000
performing iteration : 2660000
performing iteration : 2665000
performing iteration : 2670000
performing iteration : 2675000
performing iteration : 2680000
performing iteration : 2685000
performing iteration : 2690000
performing iteration : 2695000
performing iteration : 2700000
performing iteration : 2705000
performing iteration : 2710000
performing iteration : 2715000
performing iteration : 2720000
performing iteration : 2725000
performing iteration : 2730000
performing iteration : 2735000
performing iteration : 2740000
performing iteration : 2745000
performing iteration : 2750000
performing iteration : 2755000
performing iteration : 2760000
performing iteration : 2765000
performing iteration : 2770000
performing iteration : 2775000
performing iteration : 2780000
performing iteration : 2785000
performing iteration : 2790000
performing iteration : 2795000
performing iteration : 2800000
performing iteration : 2805000
performing iteration : 2810000
performing iteration : 2815000
performing iteration : 2820000
performing iteration : 2825000

performing iteration : 2830000
performing iteration : 2835000
performing iteration : 2840000
performing iteration : 2845000
performing iteration : 2850000
performing iteration : 2855000
performing iteration : 2860000
performing iteration : 2865000
performing iteration : 2870000
performing iteration : 2875000
performing iteration : 2880000
performing iteration : 2885000
performing iteration : 2890000
performing iteration : 2895000
performing iteration : 2900000
performing iteration : 2905000
performing iteration : 2910000
performing iteration : 2915000
performing iteration : 2920000
performing iteration : 2925000
performing iteration : 2930000
performing iteration : 2935000
performing iteration : 2940000
performing iteration : 2945000
performing iteration : 2950000
performing iteration : 2955000
performing iteration : 2960000
performing iteration : 2965000
performing iteration : 2970000
performing iteration : 2975000
performing iteration : 2980000
performing iteration : 2985000
performing iteration : 2990000
performing iteration : 2995000
performing iteration : 3000000
performing iteration : 3005000
performing iteration : 3010000
performing iteration : 3015000
performing iteration : 3020000
performing iteration : 3025000
performing iteration : 3030000
performing iteration : 3035000
performing iteration : 3040000
performing iteration : 3045000
performing iteration : 3050000
performing iteration : 3055000
performing iteration : 3060000
performing iteration : 3065000
performing iteration : 3070000
performing iteration : 3075000
performing iteration : 3080000
performing iteration : 3085000
performing iteration : 3090000
performing iteration : 3095000
performing iteration : 3100000
performing iteration : 3105000
performing iteration : 3110000
performing iteration : 3115000
performing iteration : 3120000
performing iteration : 3125000
performing iteration : 3130000
performing iteration : 3135000
performing iteration : 3140000
performing iteration : 3145000
performing iteration : 3150000
performing iteration : 3155000
performing iteration : 3160000
performing iteration : 3165000
performing iteration : 3170000
performing iteration : 3175000
performing iteration : 3180000
performing iteration : 3185000
performing iteration : 3190000
performing iteration : 3195000
performing iteration : 3200000
performing iteration : 3205000
performing iteration : 3210000
performing iteration : 3215000
performing iteration : 3220000
performing iteration : 3225000
performing iteration : 3230000
performing iteration : 3235000
performing iteration : 3240000
performing iteration : 3245000
performing iteration : 3250000
performing iteration : 3255000
performing iteration : 3260000
performing iteration : 3265000
performing iteration : 3270000
performing iteration : 3275000
performing iteration : 3280000
performing iteration : 3285000
performing iteration : 3290000
performing iteration : 3295000
performing iteration : 3300000
performing iteration : 3305000
performing iteration : 3310000
performing iteration : 3315000
performing iteration : 3320000
performing iteration : 3325000
performing iteration : 3330000
performing iteration : 3335000
performing iteration : 3340000
performing iteration : 3345000
performing iteration : 3350000
performing iteration : 3355000
performing iteration : 3360000
performing iteration : 3365000
performing iteration : 3370000
performing iteration : 3375000
performing iteration : 3380000
performing iteration : 3385000
performing iteration : 3390000
performing iteration : 3395000
performing iteration : 3400000
performing iteration : 3405000
performing iteration : 3410000
performing iteration : 3415000
performing iteration : 3420000
performing iteration : 3425000
performing iteration : 3430000
performing iteration : 3435000
performing iteration : 3440000
performing iteration : 3445000
performing iteration : 3450000
performing iteration : 3455000
performing iteration : 3460000
performing iteration : 3465000
performing iteration : 3470000
performing iteration : 3475000
performing iteration : 3480000
performing iteration : 3485000
performing iteration : 3490000
performing iteration : 3495000
performing iteration : 3500000
performing iteration : 3505000
performing iteration : 3510000
performing iteration : 3515000
performing iteration : 3520000
performing iteration : 3525000
performing iteration : 3530000
performing iteration : 3535000
performing iteration : 3540000
performing iteration : 3545000
performing iteration : 3550000
performing iteration : 3555000
performing iteration : 3560000
performing iteration : 3565000
performing iteration : 3570000
performing iteration : 3575000
performing iteration : 3580000
performing iteration : 3585000
performing iteration : 3590000
performing iteration : 3595000
performing iteration : 3600000
performing iteration : 3605000
performing iteration : 3610000
performing iteration : 3615000
performing iteration : 3620000
performing iteration : 3625000
performing iteration : 3630000
performing iteration : 3635000
performing iteration : 3640000
performing iteration : 3645000
performing iteration : 3650000
performing iteration : 3655000
performing iteration : 3660000
performing iteration : 3665000
performing iteration : 3670000
performing iteration : 3675000
performing iteration : 3680000
performing iteration : 3685000
performing iteration : 3690000
performing iteration : 3695000
performing iteration : 3700000
performing iteration : 3705000
performing iteration : 3710000
performing iteration : 3715000
performing iteration : 3720000
performing iteration : 3725000
performing iteration : 3730000
performing iteration : 3735000
performing iteration : 3740000
performing iteration : 3745000
performing iteration : 3750000
performing iteration : 3755000
performing iteration : 3760000
performing iteration : 3765000
performing iteration : 3770000
performing iteration : 3775000
performing iteration : 3780000
performing iteration : 3785000
performing iteration : 3790000
performing iteration : 3795000
performing iteration : 3800000
performing iteration : 3805000
performing iteration : 3810000
performing iteration : 3815000
performing iteration : 3820000
performing iteration : 3825000
performing iteration : 3830000
performing iteration : 3835000
performing iteration : 3840000
performing iteration : 3845000
performing iteration : 3850000
performing iteration : 3855000
performing iteration : 3860000
performing iteration : 3865000
performing iteration : 3870000
performing iteration : 3875000
performing iteration : 3880000
performing iteration : 3885000
performing iteration : 3890000
performing iteration : 3895000
performing iteration : 3900000
performing iteration : 3905000
performing iteration : 3910000
performing iteration : 3915000
performing iteration : 3920000
performing iteration : 3925000
performing iteration : 3930000
performing iteration : 3935000
performing iteration : 3940000
performing iteration : 3945000
performing iteration : 3950000
performing iteration : 3955000
performing iteration : 3960000
performing iteration : 3965000
performing iteration : 3970000
performing iteration : 3975000
performing iteration : 3980000
performing iteration : 3985000
performing iteration : 3990000
performing iteration : 3995000
performing iteration : 4000000
performing iteration : 4005000
performing iteration : 4010000
performing iteration : 4015000
performing iteration : 4020000
performing iteration : 4025000
performing iteration : 4030000
performing iteration : 4035000
performing iteration : 4040000
performing iteration : 4045000
performing iteration : 4050000
performing iteration : 4055000
performing iteration : 4060000
performing iteration : 4065000
performing iteration : 4070000
performing iteration : 4075000
performing iteration : 4080000
performing iteration : 4085000
performing iteration : 4090000
performing iteration : 4095000
performing iteration : 4100000
performing iteration : 4105000
performing iteration : 4110000
performing iteration : 4115000
performing iteration : 4120000
performing iteration : 4125000
performing iteration : 4130000
performing iteration : 4135000
performing iteration : 4140000
performing iteration : 4145000
performing iteration : 4150000
performing iteration : 4155000
performing iteration : 4160000
performing iteration : 4165000
performing iteration : 4170000
performing iteration : 4175000
performing iteration : 4180000
performing iteration : 4185000
performing iteration : 4190000
performing iteration : 4195000
performing iteration : 4200000
performing iteration : 4205000
performing iteration : 4210000
performing iteration : 4215000
performing iteration : 4220000
performing iteration : 4225000
performing iteration : 4230000

performing iteration : 4235000
performing iteration : 4240000
performing iteration : 4245000
performing iteration : 4250000
performing iteration : 4255000
performing iteration : 4260000
performing iteration : 4265000
performing iteration : 4270000
performing iteration : 4275000
performing iteration : 4280000
performing iteration : 4285000
performing iteration : 4290000
performing iteration : 4295000
performing iteration : 4300000
performing iteration : 4305000
performing iteration : 4310000
performing iteration : 4315000
performing iteration : 4320000
performing iteration : 4325000
performing iteration : 4330000
performing iteration : 4335000
performing iteration : 4340000
performing iteration : 4345000
performing iteration : 4350000
performing iteration : 4355000
performing iteration : 4360000
performing iteration : 4365000
performing iteration : 4370000
performing iteration : 4375000
performing iteration : 4380000
performing iteration : 4385000
performing iteration : 4390000
performing iteration : 4395000
performing iteration : 4400000
performing iteration : 4405000
performing iteration : 4410000
performing iteration : 4415000
performing iteration : 4420000
performing iteration : 4425000
performing iteration : 4430000
performing iteration : 4435000
performing iteration : 4440000
performing iteration : 4445000
performing iteration : 4450000
performing iteration : 4455000
performing iteration : 4460000
performing iteration : 4465000
performing iteration : 4470000
performing iteration : 4475000
performing iteration : 4480000
performing iteration : 4485000
performing iteration : 4490000
performing iteration : 4495000
performing iteration : 4500000
performing iteration : 4505000
performing iteration : 4510000
performing iteration : 4515000
performing iteration : 4520000
performing iteration : 4525000
performing iteration : 4530000
performing iteration : 4535000
performing iteration : 4540000
performing iteration : 4545000
performing iteration : 4550000
performing iteration : 4555000
performing iteration : 4560000
performing iteration : 4565000
performing iteration : 4570000
performing iteration : 4575000
performing iteration : 4580000
performing iteration : 4585000
performing iteration : 4590000
performing iteration : 4595000
performing iteration : 4600000
performing iteration : 4605000
performing iteration : 4610000
performing iteration : 4615000
performing iteration : 4620000
performing iteration : 4625000
performing iteration : 4630000
performing iteration : 4635000
performing iteration : 4640000
performing iteration : 4645000
performing iteration : 4650000
performing iteration : 4655000
performing iteration : 4660000
performing iteration : 4665000
performing iteration : 4670000
performing iteration : 4675000
performing iteration : 4680000
performing iteration : 4685000
performing iteration : 4690000
performing iteration : 4695000
performing iteration : 4700000
performing iteration : 4705000
performing iteration : 4710000
performing iteration : 4715000
performing iteration : 4720000
performing iteration : 4725000
performing iteration : 4730000
performing iteration : 4735000
performing iteration : 4740000
performing iteration : 4745000
performing iteration : 4750000
performing iteration : 4755000
performing iteration : 4760000
performing iteration : 4765000
performing iteration : 4770000
performing iteration : 4775000
performing iteration : 4780000
performing iteration : 4785000
performing iteration : 4790000
performing iteration : 4795000
performing iteration : 4800000
performing iteration : 4805000
performing iteration : 4810000
performing iteration : 4815000
performing iteration : 4820000
performing iteration : 4825000
performing iteration : 4830000
performing iteration : 4835000
performing iteration : 4840000
performing iteration : 4845000
performing iteration : 4850000
performing iteration : 4855000
performing iteration : 4860000
performing iteration : 4865000
performing iteration : 4870000
performing iteration : 4875000
performing iteration : 4880000
performing iteration : 4885000
performing iteration : 4890000
performing iteration : 4895000
performing iteration : 4900000
performing iteration : 4905000
performing iteration : 4910000
performing iteration : 4915000
performing iteration : 4920000
performing iteration : 4925000
performing iteration : 4930000
performing iteration : 4935000
performing iteration : 4940000
performing iteration : 4945000
performing iteration : 4950000
performing iteration : 4955000
performing iteration : 4960000
performing iteration : 4965000
performing iteration : 4970000
performing iteration : 4975000
performing iteration : 4980000
performing iteration : 4985000
performing iteration : 4990000
performing iteration : 4995000
performing iteration : 5000000
performing iteration : 5005000
performing iteration : 5010000
performing iteration : 5015000
performing iteration : 5020000
performing iteration : 5025000
performing iteration : 5030000
performing iteration : 5035000
performing iteration : 5040000
performing iteration : 5045000
performing iteration : 5050000
performing iteration : 5055000
performing iteration : 5060000
performing iteration : 5065000
performing iteration : 5070000
performing iteration : 5075000
performing iteration : 5080000
performing iteration : 5085000
performing iteration : 5090000
performing iteration : 5095000
performing iteration : 5100000
performing iteration : 5105000
performing iteration : 5110000
performing iteration : 5115000
performing iteration : 5120000
performing iteration : 5125000
performing iteration : 5130000
performing iteration : 5135000
performing iteration : 5140000

In [3]:
# db_dict

In [21]:
pd.read_csv('../data/LILA/db_export_season_all.csv')

/home/ubuntu/test_env/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,idCaptureEvent,Season,GridCell,RollNumber,CaptureEventNum,CaptureTimestamp,SequenceNum,PathFilename,NumberOfSpecies,Species,CountMedian,Standing,Resting,Moving,Eating,Interacting,Babies
0,1,1,B04,1,1,2010-07-18 16:26:14,1,S1/B04/B04_R1/PICT0001.JPG,1,human,1,0.625000,0.062500,0.000000,0.000000,0.500000,0.0
1,2,1,B04,1,2,2010-07-18 16:26:30,1,S1/B04/B04_R1/PICT0002.JPG,1,human,2,0.095238,0.619048,0.000000,0.047619,0.333333,0.0
2,3,1,B04,1,3,2010-07-20 06:14:06,1,S1/B04/B04_R1/PICT0003.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1,B04,1,4,2010-07-22 08:56:06,1,S1/B04/B04_R1/PICT0004.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1,B04,1,5,2010-07-24 01:16:28,1,S1/B04/B04_R1/PICT0005.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,1,B04,1,6,2010-07-24 08:20:10,1,S1/B04/B04_R1/PICT0006.JPG,1,gazelleGrants,1,0.000000,0.000000,1.000000,0.000000,0.000000,0.0
6,7,1,B04,1,7,2010-07-24 10:14:32,1,S1/B04/B04_R1/PICT0007.JPG,1,reedbuck,1,0.833333,0.000000,0.166667,0.000000,0.000000,0.0
7,8,1,B04,1,8,2010-07-30 03:59:42,1,S1/B04/B04_R1/PICT0008.JPG,1,dikDik,1,0.809524,0.000000,0.190476,0.000000,0.000000,0.0
8,9,1,B04,1,9,2010-07-30 05:20:22,1,S1/B04/B04_R1/PICT0009.JPG,1,zebra,1,0.937500,0.000000,0.062500,0.062500,0.000000,0.0
9,10,1,B04,1,10,2010-07-30 05:24:50,1,S1/B04/B04_R1/PICT0010.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,1,B04,1,11,2010-07-30 20:54:16,1,S1/B04/B04_R1/PICT0011.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,1,B04,1,12,2010-07-30 20:57:28,1,S1/B04/B04_R1/PICT0012.JPG,1,zebra,1,0.230769,0.000000,0.000000,0.769231,0.000000,0.0
12,13,1,B04,1,13,2010-08-01 17:35:58,1,S1/B04/B04_R1/PICT0013.JPG,1,gazelleGrants,3,0.571429,0.000000,0.428571,0.071429,0.000000,0.0
13,14,1,B04,1,14,2010-08-02 11:43:14,1,S1/B04/B04_R1/PICT0014.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,1,B04,1,15,2010-08-02 20:43:02,1,S1/B04/B04_R1/PICT0015.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,1,B04,1,16,2010-08-03 11:35:48,1,S1/B04/B04_R1/PICT0016.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,1,B04,1,17,2010-08-05 02:24:04,1,S1/B04/B04_R1/PICT0017.JPG,1,zebra,1,1.000000,0.076923,0.000000,0.000000,0.000000,0.0
17,18,1,B04,1,18,2010-08-05 02:29:02,1,S1/B04/B04_R1/PICT0018.JPG,1,zebra,1,1.000000,0.000000,0.000000,0.000000,0.000000,0.0
18,19,1,B04,1,19,2010-08-05 02:43:36,1,S1/B04/B04_R1/PICT0019.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,1,B04,1,20,2010-08-05 02:57:04,1,S1/B04/B04_R1/PICT0020.JPG,1,zebra,1,0.692308,0.076923,0.076923,0.230769,0.000000,0.0
20,21,1,B04,1,21,2010-08-06 10:51:24,1,S1/B04/B04_R1/PICT0021.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,1,B04,1,22,2010-08-10 18:35:06,1,S1/B04/B04_R1/PICT0022.JPG,1,human,1,0.400000,0.000000,0.550000,0.000000,0.050000,0.0
22,23,1,B04,1,23,2010-08-10 18:41:06,1,S1/B04/B04_R1/PICT0023.JPG,1,human,1,0.294118,0.000000,0.000000,0.000000,0.705882,0.0
23,24,1,B04,1,24,2010-08-10 18:41:30,1,S1/B04/B04_R1/PICT0024.JPG,1,human,1,0.923077,0.000000,0.076923,0.000000,0.153846,0.0
24,24,1,B04,1,24,2010-08-10 18:41:30,2,S1/B04/B04_R1/PICT0025.JPG,1,human,1,0.923077,0.000000,0.076923,0.000000,0.153846,0.0
25,24,1,B04,1,24,2010-08-10 18:41:30,3,S1/B04/B04_R1/PICT0026.JPG,1,human,1,0.923077,0.000000,0.076923,0.000000,0.153846,0.0
26,25,1,B04,1,25,2010-08-10 18:43:08,1,S1/B04/B04_R1/PICT0027.JPG,1,human,1,0.250000,0.000000,0.300000,0.000000,0.500000,0.0
27,25,1,B04,1,25,2010-08-10 18:43:08,2,S1/B04/B04_R1/PICT0028.JPG,1,human,1,0.250000,0.000000,0.300000,0.000000,0.500000,0.0
28,25,1,B04,1,25,2010-08-10 18:43:08,3,S1/B04/B04_R1/PICT0029.JPG,1,human,1,0.250000,0.000000,0.300000,0.000000,0.500000,0.0
29,26,1,B04,1,26,2010-08-10 18:44:12,1,S1/B04/B04_R1/PICT0030.JPG,1,human,1,0.166667,0.000000,1.000000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5141785,2037027,8,V10,3,17,2014-05-18 15:23:10,3,S8/V10/V10_R3/S8_V10_R3_IMAG0038.JPG,1,eland,1,0.100000,0.000000,0.900000,0.000000,0.200000,0.0
5141786,2037028,8,V10,3,18,2014-05-18 16:01:29,1,S8/V10/V10_R3/S8_V10_R3_IMAG0039.JPG,1,ostrich,1,0.183673,0.000000,0.877551,0.000000,0.000000,0.0
5141787,2037028,8,V10,3,18,2014-05-18 16:01:29,2,S8/V10/V10_R3/S8_V10_R3_IMAG0040.JPG,1,ostrich,1,0.183673,0.000000,0.877551,0.000000,0.000000,0.0
5141788,2037028,8,V10,3,18,2014-05-18 16:01:29,3,S8/V10/V10_R3/S8_V10_R3_IMAG0041.JPG,1,ostrich,1,0.183673,0.000000,0.877551,0.000000,0.000000,0.0
5141789,2037029,8,V10,3,19,2014-05-18 16:09:27,1,S8/V10/V10_R3/S8_V10_R3_IMAG0042.JPG,1,ostrich,1,0.163265,0.000000,0.653061,0.387755,0.000000,0.0
5141790,2037029,8,V10,3,19,2014-05-18 16:09:27,2,S8/V10/V10_R3/S8_V10_R3_IMAG0043.JPG,1,ostrich,1,0.163265,0.000000,0.653061,0.387755,0.000000,0.0
5141791,2037029,8,V10,3,19,2014-05-18 16:09:27,3,S8/V10/V10_R3/S8_V10_R3_IMAG0044.JPG,1,ostrich,1,0.163265,0.000000,0.653061,0.387755,0.000000,0.0
5141792,2037030,8,V10,3,20,2014-05-18 16:11:06,1,S8/V10/V10_R3/S8_V10_R3_IMAG0045.JPG,1,ostrich,1,0.200000,0.000000,0.700000,0.100000,0.000000,0.0
5141793,2037030,8,V10,3,20,2014-05-18 16:11:06,2,S8/V10/V10_R3/S8_V10_R3_IMAG0046.JPG,1,ostrich,1,0.200000,0.000000,0.700000,0.100000,0.000000,0.0
5141794,2037030,8,V10,3,20,2014-05-18 16:11:06,3,S8/V10/V10_R3/S8_V10_R3_IMAG0047.JPG,1,ostrich,1,0.200000,0.000000,0.700000,0.100000,0.000000,0.0
5141795,2037031,8,V10,3,21,2014-05-19 15:42:56,1,S8/V10/V10_R3/S8_V10_R3_IMAG0048.JPG,1,leopard,1,0.500000,0.000000,0.300000,0.000000,0.200000,0.0
5141796,2037031,8,V10,3,21,2014-05-19 15:42:56,2,S8/V10/V10_R3/S8_V10_R3_IMAG0049.JPG,1,leopard,1,0.500000,0.000000,0.300000,0.000000,0.200000,0.0
5141797,2037031,8,V10,3,21,2014-05-19 15:42:56,3,S8/V10/V10_R3/S8_V10_R3_IMAG0050.JPG,1,leopard,1,0.500000,0.000000,0.300000,0.000000,0.200000,0.0
5141798,2037032,8,V10,3,22,2014-05-19 22:39:09,1,S8/V10/V10_R3/S8_V10_R3_IMAG0051.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5141799,2037033,8,V10,3,23,2014-05-19 22:40:26,1,S8/V10/V10_R3/S8_V10_R3_IMAG0052.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5141800,2037034,8,V10,3,24,2014-05-19 22:41:47,1,S8/V10/V10_R3/S8_V10_R3_IMAG0053.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5141801,2037035,8,V10,3,25,2014-05-19 22:43:09,1,S8/V10/V10_R3/S8_V10_R3_IMAG0054.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5141802,2037036,8,V10,3,26,2014-05-19 22:44:31,1,S8/V10/V10_R3/S8_V10_R3_IMAG0055.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5141803,2037037,8,V10,3,27,2014-05-21 06:00:23,1,S8/V10/V10_R3/S8_V10_R3_IMAG0056.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5141804,2037038,8,V10,3,28,2014-05-25 12:56:40,1,S8/V10/V10_R3/S8_V10_R3_IMAG0057.JPG,1,zebra,1,0.000000,0.000000,1.000000,0.000000,0.000000,0.0
5141805,2037038,8,V10,3,28,2014-05-25 12:56:40,2,S8/V10/V10_R3/S8_V10_R3_IMAG0058.JPG,1,zebra,1,0.000000,0.000000,1.000000,0.000000,0.000000,0.0
5141806,2037038,8,V10,3,28,2014-05-25 12:56:40,3,S8/V10/V10_R3/S8_V10_R3_IMAG0059.JPG,1,zebra,1,0.000000,0.000000,1.000000,0.000000,0.000000,0.0
5141807,2037039,8,V10,3,29,2014-05-31 22:46:46,1,S8/V10/V10_R3/S8_V10_R3_IMAG0060.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5141808,2037040,8,V10,3,30,2014-06-15 14:33:57,1,S8/V10/V10_R3/S8_V10_R3_IMAG0061.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5141809,2037040,8,V10,3,30,2014-06-15 14:33:57,2,S8/V10/V10_R3/S8_V10_R3_IMAG0062.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5141810,2037040,8,V10,3,30,2014-06-15 14:33:57,3,S8/V10/V10_R3/S8_V10_R3_IMAG0063.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5141811,2037041,8,V10,3,31,2014-06-22 20:42:04,1,S8/V10/V10_R3/S8_V10_R3_IMAG0064.JPG,1,zebra,1,0.700000,0.000000,0.300000,0.000000,0.000000,0.0
5141812,2037042,8,V10,3,32,2014-07-04 13:12:41,1,S8/V10/V10_R3/S8_V10_R3_IMAG0065.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5141813,2037042,8,V10,3,32,2014-07-04 13:12:41,2,S8/V10/V10_R3/S8_V10_R3_IMAG0066.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5141814,2037042,8,V10,3,32,2014-07-04 13:12:41,3,S8/V10/V10_R3/S8_V10_R3_IMAG0067.JPG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN